# Generated by Django 3.0.2 on 2020-02-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_auto_20200131_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='image',
            field=models.ImageField(blank=True, upload_to='lecture_image'),
        ),
    ]
