# Generated by Django 3.0 on 2020-02-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_auto_20200208_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
