# Generated by Django 3.0 on 2020-02-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0009_auto_20200208_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='author',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='image',
        ),
        migrations.CreateModel(
            name='Lecture_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='lecture_image')),
                ('lectureKey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Homepage.Lecture')),
            ],
        ),
    ]
