# Generated by Django 3.0 on 2020-02-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0010_auto_20200215_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
