# Generated by Django 3.0.4 on 2020-03-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0014_auto_20200314_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='user_saved',
        ),
        migrations.AddField(
            model_name='lecture',
            name='user_saved',
            field=models.ManyToManyField(to='Homepage.Profile'),
        ),
    ]
