# Generated by Django 3.0.5 on 2020-05-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0016_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='Lecture_rate',
            new_name='lecture_rate',
        ),
        migrations.AlterField(
            model_name='rate',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
