# Generated by Django 3.0.6 on 2020-05-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0017_auto_20200503_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_views', models.CharField(max_length=100, null=True)),
                ('error_detail', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
