# Generated by Django 3.0.6 on 2020-05-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0018_errorreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_image',
            name='image',
            field=models.ImageField(upload_to='lecture_image'),
        ),
    ]
