# Generated by Django 3.0.6 on 2020-05-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0019_auto_20200511_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreport',
            name='error_massage_to_user',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
