# Generated by Django 3.0.6 on 2020-05-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0020_errorreport_error_massage_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
